widgetTheme=widget-themes/comprepronto
primaryColor=#36a9e1
secondaryColor=#86C953
labelColor=#ffffff
hideWhenOffline=
contactMail=admin@seudominio.com
loadingLabel=Carregando...
loginError=Erro de login
chatHeader=Atendimento Online
startInfo=Por favor preencha os campos para iniciar o bate-papo
widgetWidth=340
widgetHeight=520
widgetOffset=50
mobileBreakpoint=550
maxConnections=5
messageSound=audio/default.mp3
startLabel=Iniciar
backLabel=Voltar
initMessageBody=Olá, como posso ajudá-lo?
initMessageAuthor=Operador
chatInputLabel=Faça a sua pergunta
timeDaysAgo=dia(s)
timeHoursAgo=hora(s)
timeMinutesAgo=minuto(s)
timeSecondsAgo=segundo(s)
offlineMessage=Operador ficou offline
toggleSoundLabel=Som
toggleScrollLabel=Auto-scroll
toggleEmoticonsLabel=Emoticons
toggleAutoShowLabel=Auto-show
toggleFullscreenLabel=Alternar para o modo tela cheia
endChatLabel=Sair do Chat
endChatConfirmQuestion=Você tem certeza?
endChatConfirm=Yes
endChatCancel=Cancelar
contactHeader=Entre em Contato
contactInfo=Todos os operadores estão offline. Utilize o formulário abaixo para nos enviar um e-mail com a sua pergunta.
contactNameLabel=Seu nome
contactMailLabel=Seu e-mail
contactQuestionLabel=Sua Pergunta
contactSendLabel=Enviar
contactSuccessHeader=Mensagem enviada
contactSuccessMessage=Sua pergunta foi enviada. Obrigado!
contactErrorHeader=Erro
contactErrorMessage=Houve um erro ao enviar a sua pergunta
headerHeight=165
installed=
autoShowWidgetAfter=10
autoShowWidget=true
askForMail=true