<?php

// File generated by the installatio wizard
// (do not modify manually)

return array(
    
    // Database settings
    
    'dbHost'     => 'localhost',
    'dbPort'     => 3306,
    'dbUser'     => 'root',
    'dbPassword' => '',
    'dbName'     => '',
    
    // Chat application admin user
    
    'superUser' => 'admin',
    'superPass' => '12345'
);

?>
